#ifndef SCHEDULING_DATA_GENERATOR_H
#define SCHEDULING_DATA_GENERATOR_H

#include <random>
#include <string>
#include <vector>
#include <unordered_set>
#include <algorithm>
#include <chrono>

#include "structures.h"

class SchedulingDataGenerator {
private:
    std::mt19937 rng;

    // Total count: 1000 names
    std::vector<std::string> first_names = {
        "Aaliyah", "Aaron", "Abby", "Abigail", "Abraham", "Adam", "Addison", "Adeline",
        "Adrian", "Adriana", "Aiden", "Aisha", "Alaina", "Alan", "Alana", "Albert",
        "Alberto", "Aldo", "Alec", "Alejandro", "Alex", "Alexa", "Alexander", "Alexandra",
        "Alexandria", "Alexia", "Alexis", "Alfred", "Alfredo", "Ali", "Alice", "Alicia",
        "Alina", "Alisa", "Alison", "Alivia", "Allen", "Allison", "Alma", "Alondra",
        "Alvin", "Alyssa", "Amanda", "Amari", "Amaya", "Amber", "Amelia", "Amir",
        "Amos", "Amy", "Ana", "Anabelle", "Anastasia", "Anders", "Anderson", "Andre",
        "Andrea", "Andres", "Andrew", "Angel", "Angela", "Angelica", "Angelina", "Angelo",
        "Angie", "Anita", "Aniya", "Ann", "Anna", "Annabelle", "Annalise", "Anne",
        "Annette", "Annie", "Annika", "Ansley", "Anthony", "Anton", "Antonio", "Anya",
        "April", "Arabella", "Archer", "Arden", "Arely", "Ari", "Aria", "Ariana",
        "Arianna", "Ariel", "Arjun", "Arlo", "Armando", "Arthur", "Arturo", "Arya",
        "Asa", "Asher", "Ashley", "Ashton", "Aspen", "Astrid", "Athena", "Aubree",
        "Aubrey", "Audrey", "August", "Aurora", "Austin", "Autumn", "Ava", "Avery",
        "Axel", "Ayla", "Bailey", "Barbara", "Barrett", "Barry", "Beau", "Beckett",
        "Beckham", "Belinda", "Bella", "Ben", "Benjamin", "Bennett", "Bentley", "Bernard",
        "Bernice", "Beth", "Bethany", "Betty", "Beverly", "Bianca", "Bill", "Billy",
        "Blaine", "Blair", "Blaise", "Blake", "Blakely", "Blanca", "Bo", "Bob",
        "Bobby", "Bodie", "Bonnie", "Bowen", "Brad", "Braden", "Bradley", "Brady",
        "Braeden", "Braelyn", "Branden", "Brandon", "Brandy", "Brantley", "Braxton", "Brayden",
        "Breanna", "Brenda", "Brendan", "Brenna", "Brennan", "Brent", "Brett", "Brian",
        "Briana", "Brianna", "Bridget", "Brielle", "Briggs", "Brinley", "Bristol", "Brittany",
        "Brittney", "Brock", "Brodie", "Brody", "Bronson", "Brooke", "Brooklyn", "Brooks",
        "Bruce", "Bruno", "Bryan", "Bryant", "Bryce", "Brynn", "Bryson", "Byron",
        "Cade", "Caden", "Cadence", "Cael", "Caiden", "Cain", "Caitlin", "Caitlyn",
        "Cal", "Caleb", "Calhoun", "Callie", "Callum", "Calvin", "Camden", "Cameron",
        "Camila", "Camille", "Campbell", "Camryn", "Candace", "Candice", "Cannon", "Cara",
        "Carla", "Carl", "Carlos", "Carly", "Carmela", "Carmen", "Carol", "Carole",
        "Carolina", "Caroline", "Carolyn", "Carrie", "Carson", "Carter", "Case", "Casey",
        "Cash", "Cassandra", "Cassidy", "Cassius", "Catalina", "Catherine", "Cathy", "Cecelia",
        "Cecil", "Cecilia", "Celeste", "Celia", "Celine", "Cesar", "Chad", "Chance",
        "Chandler", "Chanel", "Channing", "Charity", "Charla", "Charlene", "Charles", "Charlie",
        "Charlotte", "Chase", "Chaya", "Chelsea", "Cheryl", "Chester", "Cheyenne", "Chiara",
        "Chloe", "Chris", "Christian", "Christina", "Christine", "Christopher", "Cindy", "Claire",
        "Clara", "Clarence", "Clarissa", "Clark", "Claudia", "Clay", "Clayton", "Clement",
        "Clifford", "Clifton", "Clint", "Clinton", "Clyde", "Cody", "Cohen", "Colby",
        "Cole", "Colette", "Colin", "Colleen", "Collin", "Colt", "Colton", "Conner",
        "Connor", "Conor", "Conrad", "Constance", "Cooper", "Cora", "Coralie", "Corbin",
        "Corey", "Corinne", "Cory", "Courtney", "Coy", "Craig", "Crew", "Cristian",
        "Cristina", "Crystal", "Cullen", "Curtis", "Cynthia", "Cyrus", "Daisy", "Dakota",
        "Dale", "Dallas", "Dalton", "Damian", "Damien", "Damon", "Dan", "Dana",
        "Dane", "Dangelo", "Daniel", "Daniela", "Daniella", "Danielle", "Danna", "Danny",
        "Dante", "Daphne", "Darcy", "Daria", "Darian", "Dariel", "Dario", "Darius",
        "Darlene", "Darnell", "Darrel", "Darrell", "Darren", "Darryl", "Darwin", "Dash",
        "Dave", "David", "Davian", "Davin", "Davina", "Davis", "Dawn", "Dawson",
        "Dax", "Dayana", "Dayton", "Deacon", "Dean", "Deandre", "Deanna", "Debora",
        "Deborah", "Debra", "Declan", "Deidre", "Deja", "Delaney", "Delilah", "Della",
        "Delores", "Demetrius", "Demi", "Denise", "Dennis", "Denny", "Denver", "Denzel",
        "Deon", "Derek", "Derrick", "Deshawn", "Desiree", "Desmond", "Destiny", "Devin",
        "Devon", "Dewayne", "Dexter", "Diamond", "Diana", "Diane", "Diego", "Dillon",
        "Dina", "Dion", "Dirk", "Domenic", "Dominic", "Dominick", "Dominique", "Don",
        "Donald", "Donna", "Donnell", "Donnie", "Donovan", "Dora", "Dorian", "Doris",
        "Dorothy", "Doug", "Douglas", "Drake", "Drew", "Duane", "Duke", "Dulce",
        "Duncan", "Dustin", "Dwayne", "Dwight", "Dylan", "Earl", "Easton", "Ed",
        "Eddie", "Eddy", "Eden", "Edgar", "Edison", "Edith", "Edmond", "Edmund",
        "Edna", "Eduardo", "Edward", "Edwin", "Eileen", "Elaina", "Elaine", "Eleanor",
        "Elena", "Eli", "Elian", "Eliana", "Elias", "Eliezer", "Elijah", "Elisa",
        "Elise", "Elisha", "Eliza", "Elizabeth", "Ella", "Ellen", "Elliana", "Elliot",
        "Elliott", "Ellis", "Ellison", "Elmer", "Eloise", "Elsa", "Elsie", "Elton",
        "Elvin", "Elvis", "Elyse", "Emanuel", "Ember", "Emerson", "Emery", "Emil",
        "Emilia", "Emiliano", "Emilio", "Emily", "Emma", "Emmalyn", "Emmanuel", "Emmett",
        "Emmitt", "Enrique", "Enzo", "Eric", "Erica", "Erick", "Erik", "Erika",
        "Erin", "Erma", "Ernest", "Ernesto", "Esmeralda", "Esperanza", "Esteban", "Estella",
        "Estelle", "Esther", "Ethan", "Ethel", "Eugene", "Eugenia", "Eva", "Evan",
        "Evangeline", "Evelyn", "Everett", "Everly", "Ezekiel", "Ezra", "Fabian", "Faith",
        "Fallon", "Fatima", "Faye", "Felicia", "Felicity", "Felipe", "Felix", "Fernanda",
        "Fernando", "Fidel", "Finley", "Finn", "Fiona", "Fisher", "Fletcher", "Flora",
        "Florence", "Floyd", "Flynn", "Ford", "Forrest", "Foster", "Fran", "Frances",
        "Francesca", "Francesco", "Francis", "Francisco", "Frank", "Frankie", "Franklin", "Fred",
        "Freddie", "Frederick", "Freya", "Frida", "Frieda", "Gabriel", "Gabriela", "Gabriella",
        "Gabrielle", "Gael", "Gage", "Galilea", "Gannon", "Garland", "Garrett", "Garrison",
        "Garth", "Gary", "Gatlin", "Gavin", "Gemma", "Gene", "Genesis", "Genevieve",
        "George", "Georgia", "Georgina", "Gerald", "Geraldine", "Gerard", "Gerardo", "Gia",
        "Giada", "Giancarlo", "Gianna", "Gianni", "Gibson", "Gideon", "Gigi", "Gilbert",
        "Gilberto", "Gilda", "Gillian", "Gina", "Ginger", "Gino", "Giorgio", "Giovani",
        "Giovanna", "Giovanni", "Giselle", "Giuliana", "Gladys", "Glen", "Glenda", "Glenn",
        "Gloria", "Gordon", "Grace", "Gracelyn", "Gracie", "Grady", "Graham", "Grant",
        "Grayson", "Greg", "Gregg", "Gregory", "Greta", "Gretchen", "Griffin", "Guadalupe",
        "Guillermo", "Gunnar", "Gunner", "Gus", "Gustavo", "Guy", "Gwen", "Gwendolyn",
        "Hadley", "Hailey", "Haley", "Hallie", "Hamilton", "Hana", "Hank", "Hanna",
        "Hannah", "Harley", "Harlow", "Harmony", "Harold", "Harper", "Harris", "Harrison",
        "Harry", "Harvey", "Hassan", "Hattie", "Haven", "Hayden", "Haylee", "Hayley",
        "Hazel", "Heath", "Heather", "Heaven", "Hector", "Heidi", "Helen", "Helena",
        "Hendrix", "Henley", "Henry", "Herman", "Hilary", "Hilda", "Hillary", "Holden",
        "Holland", "Hollie", "Holly", "Hope", "Howard", "Hudson", "Hugh", "Hugo",
        "Humberto", "Hunter", "Ian", "Ibrahim", "Ida", "Idris", "Ignacio", "Iker",
        "Ilana", "Iliana", "Imani", "Immanuel", "Imogen", "Inez", "Ingrid", "Ira",
        "Irene", "Iris", "Irma", "Irvin", "Irving", "Isaac", "Isabel", "Isabela",
        "Isabella", "Isabelle", "Isaiah", "Isaias", "Ishaan", "Ismael", "Israel", "Issac",
        "Ivan", "Ivana", "Ivor", "Ivory", "Ivy", "Izabella", "Jace", "Jack",
        "Jackie", "Jackson", "Jacob", "Jacqueline", "Jacquelyn", "Jada", "Jade", "Jaden",
        "Jadiel", "Jagger", "Jaime", "Jair", "Jairo", "Jake", "Jakob", "Jalen",
        "Jamal", "Jamar", "James", "Jameson", "Jamie", "Jana", "Janae", "Jane",
        "Janelle", "Janessa", "Janet", "Janice", "Janie", "Janine", "Jared", "Jarrett",
        "Jarvis", "Jase", "Jasmine", "Jason", "Jasper", "Javier", "Javion", "Jax",
        "Jaxon", "Jaxson", "Jay", "Jayce", "Jayda", "Jayden", "Jayla", "Jayleen",
        "Jaylen", "Jaylin", "Jayson", "Jazlyn", "Jazmin", "Jazmine", "Jean", "Jeanette",
        "Jeanine", "Jeanne", "Jedidiah", "Jeff", "Jefferson", "Jeffery", "Jeffrey", "Jemma",
        "Jenna", "Jennie", "Jennifer", "Jenny", "Jensen", "Jeremiah", "Jeremy", "Jermaine",
        "Jerome", "Jerry", "Jesenia", "Jesse", "Jessica", "Jessie", "Jesus", "Jett",
        "Jillian", "Jim", "Jimmy", "Jo", "Joan", "Joanna", "Joanne", "Joaquin",
        "Jocelyn", "Joe", "Joel", "Joelle", "Joey", "Johan", "Johanna", "John",
        "Johnathan", "Johnny", "Jolene", "Jolie", "Jon", "Jonah", "Jonas", "Jonathan",
        "Jones", "Jordan", "Jordyn", "Jorge", "Jose", "Josefina", "Joseph", "Josephine",
        "Joshua", "Josiah", "Josie", "Josue", "Journey", "Jovan", "Jovani", "Joy",
        "Joyce", "Juan", "Juana", "Juanita", "Judah", "Judd", "Jude", "Judith",
        "Judy", "Jules", "Julia", "Julian", "Juliana", "Julianna", "Julianne", "Julie",
        "Julien", "Juliet", "Juliette", "Julio", "Julissa", "Julius", "June", "Junior",
        "Juniper", "Justin", "Justine", "Kade", "Kaden", "Kai", "Kaia", "Kaiden",
        "Kailey", "Kailyn", "Kaitlin", "Kaitlyn", "Kaiya", "Kaleb", "Kali", "Kamari",
        "Kamden", "Kameron", "Kamila", "Kamryn", "Kane", "Kara", "Karen", "Kari",
        "Karina", "Karla", "Karlee", "Karlie", "Karsyn", "Karter", "Kasey", "Kash",
        "Kason", "Kassandra", "Kassidy", "Kate", "Katelyn", "Katelynn", "Katherine", "Kathleen",
        "Kathryn", "Kathy", "Katie", "Katrina", "Katy", "Kay", "Kaya", "Kayden",
        "Kaydence", "Kayla", "Kaylee", "Kayleigh", "Kayson", "Keagan", "Keaton", "Keegan",
        "Keely", "Keenan", "Keira", "Keith", "Kellan", "Kellen", "Kelley", "Kelli",
        "Kellie", "Kelly", "Kelsey", "Kelvin", "Ken", "Kendall", "Kendra", "Kendrick",
        "Kenna", "Kennedy", "Kenneth", "Kenny", "Kensley", "Kent", "Kenton", "Kenya",
        "Kenzie", "Kerri", "Kerry", "Kevin", "Khalid", "Khalil", "Khloe", "Kian",
        "Kiana", "Kiara", "Kiefer", "Kieran", "Kierra", "Kiersten", "Kim", "Kimber",
        "Kimberly", "Kingsley", "Kingston", "Kinley", "Kinsley", "Kip", "Kira", "Kirby",
        "Kirk", "Kirsten", "Kobe", "Kody", "Kolby", "Kolten", "Kolton", "Korbin",
        "Kourtney", "Kristen", "Kristin", "Kristina", "Kristine", "Kristopher", "Kristy", "Krystal",
        "Kurt", "Kurtis", "Kyla", "Kyle", "Kylee", "Kyleigh", "Kyler", "Kylie",
        "Kyra", "Kyrie", "Lacey", "Laila", "Lainey", "Lamar", "Lambert", "Lamont",
        "Lana", "Lance", "Landen", "Landon", "Landry", "Lane", "Laney", "Langston",
        "Lara", "Larissa", "Larry", "Lars", "Laura", "Laurel", "Lauren", "Laurence",
        "Laurie", "Lawrence", "Lawson", "Layla", "Layne", "Layton", "Lea", "Leah",
        "Leandro", "Leann", "Leanna", "Leanne", "Ledger", "Lee", "Leif", "Leigh",
        "Leila", "Leilani", "Lela", "Leland", "Lena", "Lennon", "Lennox", "Lenora",
        "Leo", "Leon", "Leona", "Leonard", "Leonardo", "Leone", "Leonel", "Leonidas",
        "Leopold", "Leora", "Leroy", "Lesley", "Leslie", "Lester", "Leticia", "Levi",
        "Lewis", "Lexi", "Lexie", "Lexus", "Lia", "Liam", "Liana", "Libby",
        "Liberty", "Lila", "Lilah", "Lilian", "Liliana", "Lilith", "Lillian", "Lilliana",
        "Lillie", "Lilly", "Lily", "Lincoln", "Linda", "Lindsay", "Lindsey", "Linus",
        "Lionel", "Lisa", "Lisette", "Litzy", "Liv", "Livia", "Liz", "Liza",
        "Lizbeth", "Lizette", "Lloyd", "Logan", "Lois", "Lola", "London", "Lonnie",
        "Lora", "Loraine", "Loren", "Lorena", "Lorenzo", "Loretta", "Lori", "Lorna",
        "Lorraine", "Lou", "Louie", "Louis", "Louisa", "Louise", "Lourdes", "Lowell",
        "Luca", "Lucas", "Lucia", "Lucian", "Luciana", "Luciano", "Lucille", "Lucy",
        "Luis", "Luka", "Lukas", "Luke", "Luna", "Luz", "Lydia", "Lyla",
        "Lyle", "Lynda", "Lynn", "Lynne", "Lynnette", "Lyric", "Mabel", "Mabelle",
        "Macey", "Macie", "Mack", "Mackenzie", "Macy", "Madalyn", "Madden", "Maddison",
        "Maddox", "Madeleine", "Madeline", "Madelyn", "Madison", "Madisyn", "Mae", "Maeve",
        "Magdalena", "Maggie", "Magnolia", "Maia", "Maisy", "Makai", "Makayla", "Makenna",
        "Makenzie", "Malachi", "Malakai", "Malcolm", "Maleah", "Malia", "Malik", "Malinda",
        "Mallory", "Mandy", "Manuel", "Manuela", "Mara", "Marc", "Marcel", "Marcela",
        "Marcella", "Marcelo", "Marcia", "Marco", "Marcos", "Marcus", "Marcy", "Margaret",
        "Margarita", "Margo", "Maria", "Mariah", "Mariam", "Marian", "Mariana", "Marianne",
        "Mariano", "Maribel", "Marie", "Mariela", "Marilyn", "Marina", "Mario", "Marion",
        "Marisa", "Marisol", "Marissa", "Maritza", "Marjorie", "Mark", "Marla", "Marlene",
        "Marley", "Marlon", "Marques", "Marquis", "Marsha", "Marshall", "Martha", "Martin",
        "Martina", "Martinez", "Marty", "Marvin", "Mary", "Maryam", "Maryann", "Maryjane",
        "Mason", "Mateo", "Mathew", "Mathias", "Matilda", "Matteo", "Matthew", "Matt",
        "Mattie", "Maureen", "Maurice", "Mauricio", "Mauro", "Maverick", "Mavis", "Max",
        "Maxim", "Maximilian", "Maximiliano", "Maximo", "Maximus", "Maxwell", "May", "Maya",
        "Mayer", "Mayra", "Mckenna", "Mckenzie", "Mckinley", "Meadow", "Meagan", "Meghan",
        "Megan", "Mekhi", "Mel", "Melanie", "Melany", "Melina", "Melinda", "Melissa",
        "Melody", "Melvin", "Mercedes", "Meredith", "Merrick", "Mia", "Micah", "Michael",
        "Michaela", "Michele", "Michelle", "Mickey", "Miguel", "Mikaela", "Mike", "Mila",
        "Milan", "Milani", "Milania", "Mildred", "Miles", "Miller", "Millie", "Milo",
        "Milton", "Mina", "Mindy", "Mira", "Miracle", "Miranda", "Miriam", "Misael",
        "Misty", "Mitch", "Mitchell", "Mohamed", "Mohammad", "Mohammed", "Moira", "Moises",
        "Mollie", "Molly", "Mona", "Monica", "Monique", "Monroe", "Monserrat", "Montana",
        "Monte", "Montgomery", "Monty", "Morgan", "Moriah", "Morris", "Moses", "Moshe",
        "Murphy", "Murray", "Mya", "Myah", "Myla", "Myles", "Myra", "Nadia",
        "Nadine", "Nancy", "Naomi", "Nash", "Nasir", "Natalia", "Natalie", "Natasha",
        "Nathalie", "Nathan", "Nathanael", "Nathaniel", "Nathen", "Nayeli", "Neal", "Ned",
        "Nehemiah", "Neil", "Nellie", "Nelly", "Nelson", "Nettie", "Nevaeh", "Nia",
        "Nicholas", "Nichole", "Nick", "Nickolas", "Nico", "Nicole", "Nicolette", "Nigel",
        "Nikhil", "Nikki", "Niko", "Nikolai", "Nikolas", "Nila", "Nina", "Nixon",
        "Noah", "Noe", "Noel", "Noelle", "Noemi", "Nola", "Nolan", "Nora",
        "Norah", "Norbert", "Norma", "Norman", "Nova", "Nyla", "Oakley", "Octavia",
        "Octavio", "Odin", "Odyssey", "Olive", "Oliver", "Olivia", "Ollie", "Omar",
        "Ophelia", "Orion", "Orlando", "Orville", "Oscar", "Osvaldo", "Oswaldo", "Otis",
        "Otto", "Owen", "Pablo", "Paige", "Paisley", "Palmer", "Paloma", "Pamela",
        "Paola", "Paris", "Parker", "Pascal", "Pat", "Patience", "Patrice", "Patricia",
        "Patrick", "Patsy", "Patti", "Patty", "Paul", "Paula", "Paulina", "Pauline",
        "Paxton", "Payton", "Pearl", "Pedro", "Peggy", "Penelope", "Penny", "Percy",
        "Perla", "Perry", "Pete", "Peter", "Peyton", "Phil", "Philip", "Phillip",
        "Phoebe", "Phoenix", "Phyllis", "Pierce", "Pierre", "Piper", "Polo", "Poppy",
        "Porter", "Portia", "Precious", "Presley", "Preston", "Prince", "Princess", "Princeton",
        "Priscilla", "Promise", "Prudence", "Quentin", "Quincy", "Quinn", "Quinton", "Rachael",
        "Rachel", "Rachelle", "Rafael", "Raiden", "Raina", "Ralph", "Ramiro", "Ramon",
        "Ramona", "Ramsey", "Randall", "Randolph", "Randy", "Raquel", "Rashad", "Raul",
        "Raven", "Ray", "Raylan", "Raymond", "Rayna", "Reagan", "Rebeca", "Rebecca",
        "Rebekah", "Reese", "Regan", "Reggie", "Regina", "Reginald", "Reid", "Reign",
        "Reina", "Remi", "Remington", "Remy", "Rena", "Renata", "Rene", "Renee",
        "Reuben", "Rex", "Rey", "Reyna", "Reynold", "Rhett", "Rhiannon", "Rhoda",
        "Rhonda", "Ria", "Ricardo", "Richard", "Rick", "Rickey", "Rickie", "Ricky",
        "Rico", "Rider", "Ridge", "Riggs", "Riley", "Rita", "River", "Rob",
        "Robbie", "Robert", "Roberto", "Robin", "Robyn", "Rocco", "Rochelle", "Rocky",
        "Rod", "Rodger", "Rodney", "Rodolfo", "Rodrigo", "Rogelio", "Roger", "Rohan",
        "Roland", "Rolando", "Roman", "Romeo", "Ron", "Ronald", "Ronan", "Ronda",
        "Ronin", "Ronnie", "Roosevelt", "Rory", "Rosa", "Rosalie", "Rosalind", "Rosalyn",
        "Rosanna", "Rosario", "Rose", "Rosalie", "Rosemary", "Rosendo", "Rosie", "Ross",
        "Rowan", "Rowen", "Roxanne", "Roxie", "Roy", "Royal", "Royce", "Ruben",
        "Ruby", "Rudolph", "Rudy", "Rue", "Rufus", "Rupert", "Russell", "Ruth",
        "Ryan", "Ryann", "Ryder", "Ryker", "Rylan", "Ryland", "Rylee", "Ryleigh",
        "Ryley", "Sabrina", "Sade", "Sadie", "Sage", "Said", "Saige", "Sal",
        "Salem", "Salma", "Salvador", "Salvatore", "Sam", "Samantha", "Samara", "Samir",
        "Sammy", "Samson", "Samuel", "Sandra", "Sandy", "Santiago", "Santino", "Santos",
        "Sara", "Sarah", "Sarai", "Sariah", "Sasha", "Saul", "Savanna", "Savannah",
        "Sawyer", "Scarlet", "Scarlett", "Schuyler", "Scott", "Scottie", "Seamus", "Sean",
        "Sebastian", "Selah", "Selena", "Selene", "Selma", "Sergio", "Seth", "Shade",
        "Shaina", "Shamar", "Shameka", "Shamika", "Shana", "Shane", "Shania", "Shanice",
        "Shaniya", "Shannon", "Shantel", "Shaquille", "Shari", "Sharon", "Shaun", "Shauna",
        "Shawn", "Shawna", "Shay", "Shayla", "Shayne", "Shea", "Sheena", "Sheila",
        "Shelby", "Sheldon", "Shelia", "Shelley", "Shelly", "Shemar", "Sheri", "Sherman",
        "Sherri", "Sherrie", "Sherry", "Sheryl", "Shiloh", "Shirley", "Sidney", "Siena",
        "Sienna", "Sierra", "Silas", "Silvia", "Simeon", "Simon", "Simone", "Sincere",
        "Sinead", "Sky", "Skye", "Skyla", "Skylar", "Skyler", "Slade", "Sloan",
        "Sloane", "Sofia", "Sol", "Solomon", "Sondra", "Sonia", "Sonny", "Sonya",
        "Sophia", "Sophie", "Spencer", "Stacey", "Staci", "Stacie", "Stacy", "Stanley",
        "Stefan", "Stefanie", "Stella", "Stephan", "Stephanie", "Stephen", "Sterling", "Steve",
        "Steven", "Stevie", "Stewart", "Stone", "Storm", "Stuart", "Sue", "Sullivan",
        "Summer", "Susan", "Susana", "Susanna", "Susanne", "Susie", "Suzanne", "Sven",
        "Sybil", "Sydney", "Sydnee", "Sylas", "Sylvan", "Sylvester", "Sylvia", "Tabitha",
        "Talia", "Talon", "Tamara", "Tamera", "Tami", "Tamia", "Tamika", "Tammy",
        "Tania", "Tanner", "Tanya", "Tara", "Taryn", "Tasha", "Tate", "Tatiana",
        "Tatum", "Taurus", "Tavian", "Taylor", "Teagan", "Ted", "Teddy", "Teo",
        "Terence", "Teresa", "Terrance", "Terrell", "Terrence", "Terry", "Tess", "Tessa",
        "Tevin", "Thad", "Thaddeus", "Thalia", "Thea", "Thelma", "Theo", "Theodore",
        "Theresa", "Therese", "Thomas", "Tia", "Tiana", "Tierra", "Tiffany", "Tim",
        "Timothy", "Tina", "Tisha", "Titus", "Tobias", "Toby", "Todd", "Tom",
        "Tomas", "Tommy", "Toni", "Tonia", "Tony", "Tonya", "Tori", "Trace",
        "Tracey", "Traci", "Tracie", "Tracy", "Travis", "Trent", "Trenton", "Trevor",
        "Trey", "Trevon", "Treyton", "Trina", "Trinity", "Tripp", "Trisha", "Tristan",
        "Tristen", "Tristin", "Triston", "Troy", "Truman", "Tucker", "Turner", "Ty",
        "Tylan", "Tyler", "Tylor", "Tyra", "Tyree", "Tyrell", "Tyrese", "Tyrone",
        "Tyson", "Ulises", "Ulysses", "Uma", "Uriah", "Uriel", "Ursula", "Val",
        "Valentin", "Valentina", "Valentine", "Valentino", "Valeria", "Valerie", "Valery", "Van",
        "Vance", "Vanessa", "Vaughn", "Veda", "Vera", "Verne", "Vernon", "Veronica",
        "Vicky", "Victor", "Victoria", "Vida", "Vidal", "Vienna", "Vince", "Vincent",
        "Vincenzo", "Viola", "Violet", "Virgil", "Virginia", "Vivian", "Viviana", "Vivienne",
        "Vladimir", "Wade", "Walker", "Wallace", "Walter", "Wanda", "Warren", "Watson",
        "Waylon", "Wayne", "Wendell", "Wendy", "Wesley", "Westin", "Weston", "Whitney",
        "Will", "Willard", "William", "Willie", "Willis", "Willow", "Wilma", "Wilson",
        "Winfred", "Winifred", "Winnie", "Winston", "Winter", "Wyatt", "Xander", "Xavier",
        "Ximena", "Xzavier", "Yadiel", "Yahir", "Yakira", "Yamilet", "Yareli", "Yaretzi",
        "Yasmin", "Yasmine", "Yazmin", "Yehuda", "Yelena", "Yesenia", "Yolanda", "Yosef",
        "Youssef", "Yusuf", "Yvette", "Yvonne", "Zac", "Zachariah", "Zachary", "Zachery",
        "Zack", "Zackary", "Zahra", "Zaide", "Zain", "Zainab", "Zander", "Zane",
        "Zara", "Zaria", "Zariah", "Zavier", "Zayla", "Zayn", "Zayne", "Zeb",
        "Zeke", "Zelda", "Zella", "Zena", "Zendaya", "Zion", "Zoe", "Zoey",
        "Zoie", "Zola", "Zuri"
    };

    // Total count: 1000 last names
    std::vector<std::string> last_names = {
        "Abbott", "Abdullah", "Acevedo", "Acosta", "Adams", "Adkins", "Aguilar", "Aguirre",
        "Ahmad", "Ahmed", "Akers", "Akin", "Alaniz", "Alarcon", "Albert", "Albright",
        "Alcaraz", "Alexander", "Alford", "Ali", "Allen", "Allison", "Almanza", "Alonso",
        "Alston", "Alvarado", "Alvarez", "Amos", "Andersen", "Anderson", "Andrade", "Andrews",
        "Anthony", "Archer", "Arellano", "Arias", "Armstrong", "Arnold", "Arroyo", "Ashley",
        "Ashton", "Atkins", "Atkinson", "Austin", "Avery", "Avila", "Ayala", "Ayers",
        "Bacon", "Bailey", "Baird", "Baker", "Baldwin", "Ball", "Ballard", "Banks",
        "Barajas", "Barber", "Barker", "Barlow", "Barnes", "Barnett", "Barr", "Barrera",
        "Barrett", "Barron", "Barry", "Bartlett", "Barton", "Bass", "Bates", "Bauer",
        "Bautista", "Baxter", "Bean", "Beard", "Beasley", "Beck", "Becker", "Beckham",
        "Becnel", "Bedolla", "Belanger", "Belcher", "Bell", "Beltran", "Benitez", "Benjamin",
        "Bennett", "Benson", "Bentley", "Benton", "Berg", "Berger", "Bernard", "Bernstein",
        "Berry", "Best", "Betts", "Beyer", "Bhatt", "Biggs", "Billings", "Bird",
        "Bishop", "Black", "Blackburn", "Blackwell", "Blair", "Blake", "Blanchard", "Bland",
        "Blankenship", "Blevins", "Bloom", "Blue", "Bock", "Boggs", "Bolin", "Bolton",
        "Bond", "Bonilla", "Booker", "Boone", "Booth", "Borders", "Boswell", "Boucher",
        "Bourgeois", "Bowen", "Bowers", "Bowman", "Boyd", "Boyer", "Boyle", "Bradford",
        "Bradley", "Bradshaw", "Brady", "Branch", "Brandt", "Brantley", "Braun", "Bray",
        "Brennan", "Brewer", "Bridges", "Briggs", "Bright", "Britt", "Brock", "Brooks",
        "Broussard", "Brown", "Browning", "Bruce", "Bryan", "Bryant", "Buchanan", "Buck",
        "Buckley", "Bullock", "Burch", "Burdick", "Burgess", "Burke", "Burks", "Burnett",
        "Burns", "Burris", "Burt", "Burton", "Bush", "Butler", "Byrd", "Caballero",
        "Cabrera", "Cain", "Calderon", "Caldwell", "Calhoun", "Callahan", "Calvert", "Camacho",
        "Cameron", "Campbell", "Campos", "Cannon", "Cano", "Cantrell", "Cantu", "Cardenas",
        "Carey", "Carlson", "Carney", "Carpenter", "Carr", "Carrasco", "Carrillo", "Carroll",
        "Carson", "Carter", "Cartwright", "Carver", "Case", "Casey", "Cash", "Castaneda",
        "Castillo", "Castro", "Cervantes", "Chacon", "Chambers", "Chan", "Chandler", "Chaney",
        "Chang", "Chapman", "Charles", "Chase", "Chavez", "Chen", "Cheng", "Cherry",
        "Cho", "Choi", "Christensen", "Christian", "Chu", "Chung", "Church", "Cisneros",
        "Clark", "Clarke", "Clay", "Clayton", "Clements", "Clemons", "Cleveland", "Cline",
        "Cobb", "Cochran", "Cody", "Coffey", "Coffman", "Cohen", "Cole", "Coleman",
        "Collier", "Collins", "Colon", "Combs", "Compton", "Conley", "Connelly", "Conner",
        "Connor", "Conrad", "Contreras", "Conway", "Cook", "Cooke", "Cooley", "Cooper",
        "Copeland", "Corbett", "Cordero", "Cordova", "Cornejo", "Cornell", "Corona", "Correa",
        "Cortez", "Cosby", "Costa", "Costello", "Cote", "Cotton", "Couch", "Coulter",
        "Courtney", "Covington", "Cox", "Coyle", "Craig", "Crane", "Crawford", "Creech",
        "Crenshaw", "Crews", "Crisp", "Crocker", "Cromwell", "Crosby", "Cross", "Crow",
        "Crowder", "Crowe", "Crowley", "Cruz", "Cuellar", "Cuevas", "Cullen", "Cummings",
        "Cunningham", "Curry", "Curtis", "Cushman", "Dahl", "Dalton", "Daniel", "Daniels",
        "Darby", "Daugherty", "Davenport", "David", "Davidson", "Davies", "Davis", "Dawson",
        "Day", "De la Cruz", "De Leon", "Dean", "Decker", "Dejesus", "Delacruz", "Delgado",
        "Demarco", "Dempsey", "Dennis", "Denton", "Desai", "Duarte", "Dubois", "Dudley",
        "Duffy", "Duke", "Dukes", "Duncan", "Dunlap", "Dunn", "Duran", "Durham",
        "Dutta", "Duvall", "Dwyer", "Dyer", "Eaton", "Ebert", "Echevarria", "Edwards",
        "Egan", "Elder", "Elias", "Elliott", "Ellis", "Ellison", "Emerson", "Engel",
        "England", "English", "Erickson", "Ervin", "Escobar", "Esparza", "Espinal", "Espino",
        "Espinosa", "Espinoza", "Esposito", "Esquivel", "Estes", "Estrada", "Estrella", "Eubanks",
        "Evans", "Everett", "Ewing", "Fagan", "Fairchild", "Falcon", "Fanning", "Farley",

        "Farmer", "Farr", "Farrell", "Faulkner", "Fay", "Felix", "Feng", "Ferguson",
        "Fernandez", "Ferreira", "Ferrell", "Ferrer", "Ferraro", "Ferry", "Fields", "Figueroa",
        "Finch", "Finley", "Finn", "Fischer", "Fisher", "Fitzgerald", "Fitzpatrick", "Flanagan", "Fleming",
        "Fletcher", "Flores", "Flowers", "Floyd", "Flynn", "Foley", "Fong", "Fonseca",
        "Fontaine", "Foote", "Forbes", "Ford", "Foreman", "Forrest", "Forster", "Foster",
        "Fountain", "Fowler", "Fox", "Francis", "Franco", "Frank", "Franklin", "Franks",
        "Frazier", "Frederick", "Freeman", "French", "Freund", "Frey", "Friedman", "Fritz",
        "Frost", "Fry", "Frye", "Fuentes", "Fuller", "Fulton", "Fung", "Gabriel",
        "Gaffney", "Gage", "Gagnon", "Gaines", "Gallagher", "Gallegos", "Gallo", "Galvan",
        "Gamble", "Gamboa", "Gao", "Garcia", "Gardner", "Garland", "Garner", "Garrett",
        "Garrison", "Garza", "Gaston", "Gates", "Gay", "Gentry", "George", "Gerard",
        "Gerber", "German", "Gibbons", "Gibbs", "Gibson", "Gifford", "Gilbert", "Giles",
        "Gill", "Gillespie", "Gilman", "Gilmore", "Giron", "Givens", "Glass", "Gleason",

        "Glenn", "Glover", "Godfrey", "Godwin", "Goetz", "Goff", "Gold", "Goldberg",
        "Golden", "Goldman", "Goldsmith", "Gomes", "Gomez", "Gonzales", "Gonzalez", "Good",
        "Goodman", "Goodrich", "Goodwin", "Gordon", "Gore", "Gorman", "Goss", "Gough",
        "Gould", "Goyal", "Grace", "Grady", "Graham", "Grant", "Graves", "Gray",
        "Green", "Greene", "Greer", "Gregory", "Gresham", "Griffin", "Griffith", "Grimes",
        "Gross", "Grover", "Grubbs", "Gruber", "Guerrero", "Guevara", "Guido", "Gupta",
        "Guthrie", "Gutierrez", "Guzman", "Ha", "Haas", "Hacker", "Haddad", "Hadley",
        "Hagan", "Hager", "Hahn", "Haines", "Hale", "Haley", "Hall", "Hamed",
        "Hamilton", "Hamlin", "Hammond", "Hampton", "Hamrick", "Han", "Hancock", "Hand",
        "Haney", "Hanna", "Hannah", "Hansen", "Hanson", "Hardin", "Harding", "Hardy",
        "Hargrove", "Harkins", "Harlow", "Harman", "Harmon", "Harper", "Harrell", "Harrington",
        "Harris", "Harrison", "Hart", "Hartman", "Harvey", "Hassan", "Hastings", "Hatch",
        "Hatcher", "Hatfield", "Hathaway", "Hawkins", "Hawley", "Hayden", "Hayes", "Haynes",
        "Hays", "Head", "Heard", "Heath", "Hebert", "Hedrick", "Heller", "Helton",
        "Henderson", "Hendricks", "Hendrix", "Henry", "Hensley", "Henson", "Herman", "Hernandez",

        "Herrera", "Herring", "Hess", "Hester", "Hewitt", "Hickey", "Hicks", "Higgins",
        "High", "Hill", "Hilton", "Hines", "Hinton", "Ho", "Hoang", "Hobbs",
        "Hodge", "Hodges", "Hoffman", "Hogan", "Holcomb", "Holden", "Holder", "Holland",
        "Hollingsworth", "Hollis", "Holloway", "Holman", "Holmes", "Holt", "Holton", "Hood",
        "Hooker", "Hooks", "Hooper", "Hoover", "Hopkins", "Hopper", "Horn", "Horne",
        "Horner", "Horton", "Hoskins", "Houghton", "House", "Houser", "Houston", "Howard",
        "Howe", "Howell", "Hsu", "Hu", "Huang", "Hubbard", "Huber", "Hudson",
        "Huerta", "Huff", "Huffman", "Hughes", "Huynh", "Hull", "Humphrey", "Hunt",
        "Hunter", "Hurd", "Hurley", "Hurst", "Hussain", "Hussey", "Hutchinson", "Hwang",
        "Hyde", "Ibarra", "Ingram", "Iqbal", "Irizarry", "Irvin", "Irvine", "Irwin",
        "Islam", "Ivanov", "Iverson", "Ivey", "Izquierdo", "Jablonski", "Jack", "Jackson",
        "Jacobs", "Jacobson", "Jain", "James", "Jansen", "Janssen", "Jauregui", "Javier",

        "Jay", "Jeffers", "Jefferson", "Jeffries", "Jenkins", "Jennings", "Jensen", "Jeter",
        "Jiang", "Jimenez", "Jin", "Johansen", "Johnson", "Johnston", "Joiner", "Jolly",
        "Jones", "Jordan", "Jorgensen", "Joseph", "Joyce", "Juarez", "Judd", "Jude",
        "Judge", "Jung", "Justice", "Kahn", "Kaiser", "Kane", "Kang", "Kaplan",
        "Kapur", "Katz", "Kaufman", "Kay", "Kaye", "Kazmi", "Kearney", "Keating",
        "Keen", "Keenan", "Keene", "Keith", "Keller", "Kelley", "Kellogg", "Kelly",
        "Kemp", "Kendall", "Kendrick", "Kennedy", "Kenney", "Kent", "Kerr", "Kessler",
        "Key", "Khan", "Kidd", "Kilgore", "Kilpatrick", "Kim", "Kimball", "Kimbrough",
        "King", "Kinney", "Kirby", "Kirk", "Kirkland", "Kirkpatrick", "Klein", "Kline",
        "Knapp", "Knight", "Knowles", "Knox", "Ko", "Koch", "Koehler", "Koenig",
        "Kohl", "Kohler", "Kohn", "Kowalski", "Kramer", "Kraus", "Krause", "Kravitz",
        "Krueger", "Kruger", "Kuhn", "Kumar", "Kuo", "Kurtz", "Kwan", "Kwon",
        "Kyle", "La", "Lacey", "Lackey", "Lacy", "Laird", "Lake", "Lam",
        "Lamar", "Lamb", "Lambert", "Lancaster", "Landry", "Lane", "Lang", "Lange",
        "Langley", "Lara", "Larsen", "Larson", "Lassiter", "Latham", "Latif", "Lau",
        "Laughlin", "Lauria", "Law", "Lawrence", "Lawson", "Le", "Leach", "Leal",
        "Leary", "Leavitt", "Leblanc", "Ledbetter", "Lee", "Lefebvre", "Leger", "Lehman",
        "Leigh", "Leitner", "Lemieux", "Lemus", "Lentz", "Leon", "Leonard", "Leone",
        "Lester", "Leung", "Levin", "Levine", "Levy", "Lewis", "Li", "Liang",
        "Liao", "Licht", "Lieu", "Lim", "Lin", "Lincoln", "Lind", "Lindberg",
        "Linder", "Lindgren", "Lindley", "Lindsay", "Lindsey", "Link", "Linton", "Lippincott",
        "Lister", "Little", "Liu", "Livingston", "Lloyd", "Lo", "Locke", "Lockhart",
        "Lockwood", "Loftus", "Logan", "Lombardi", "Lombardo", "London", "Long", "Longo",
        "Loomis", "Lopez", "Lord", "Lorenz", "Lott", "Lou", "Louis", "Love",
        "Lovelace", "Lovell", "Low", "Lowe", "Lowery", "Lowry", "Lu", "Lucas",
        "Lugo", "Lujan", "Luna", "Lund", "Lundy", "Luo", "Lutz", "Lyle",
        "Lynch", "Lynn", "Lyon", "Lyons", "Ma", "Macdonald", "Macias", "Mack",
        "MacKenzie", "MacLeod", "Madden", "Maddox", "Madera", "Madison", "Madrigal", "Madsen",
        "Maestas", "Magana", "Magee", "Mahaffey", "Mahan", "Maher", "Mahoney", "Mai",
        "Maier", "Major", "Maldonado", "Malik", "Mallory", "Malone", "Maloney", "Mancini",
        "Mangum", "Mann", "Manning", "Mansfield", "Manuel", "Manzo", "Maples", "Marable",
        "March", "Marcum", "Marcus", "Marino", "Mark", "Marks", "Marquez", "Marsh",
        "Marshall", "Martin", "Martinez", "Marx", "Mason", "Massey", "Masters", "Mata",
        "Mathews", "Mathis", "Matos", "Matson", "Matthews", "Mattingly", "Maurer", "Mauro",
        "Maxwell", "May", "Mayer", "Mayes", "Mayfield", "Maynard", "Mayo", "Mays",
        "McAdams", "McAllister", "McArthur", "McBride", "McCabe", "McCain", "McCall", "McCallum",
        "McCann", "McCarthy", "McCarty", "McClain", "McClellan", "McClure", "McConnell", "McCormick",
        "McCoy", "McDaniel", "McDonald", "McDonnell", "McDowell", "McElroy", "McEwen", "McFadden",
        "McFarland", "McGee", "McGill", "McGinnis", "McGrath", "McGregor", "McGuire", "McIntosh",
        "McIntyre", "McKee", "McKenzie", "McKinley", "McKinney", "McKnight", "McLaughlin", "McLean",
        "McLeod", "McMahon", "McMillan", "McMullen", "McNally", "McNamara", "McNeal", "McNeil",
        "McPherson", "McQueen", "McRae", "Mead", "Meade", "Meadows", "Means", "Mejia",
        "Melendez", "Mello", "Melton", "Melvin", "Mena", "Mendez", "Mendoza", "Mercado",
        "Mercer", "Meredith", "Merrill", "Merritt", "Mesa", "Messina", "Metcalf", "Metz",
        "Meyer", "Meyers", "Michael", "Michaels", "Michaud", "Michel", "Middleton", "Mies",
        "Milan", "Miles", "Miller", "Mills", "Milton", "Miner", "Miranda", "Mireles",
        "Mitchell", "Mixon", "Miyazaki", "Moeller", "Moffett", "Mohamed", "Mohammed", "Molina",
        "Monaghan", "Monahan", "Monroe", "Montague", "Montalvo", "Montanez", "Montano", "Montes",
        "Montez", "Montgomery", "Montoya", "Moody", "Moon", "Mooney", "Moore", "Mora",
        "Morales", "Moran", "Moreau", "Moreland", "Moreno", "Morgan", "Morin", "Morley",
        "Morris", "Morrison", "Morrow", "Morse", "Morton", "Moser", "Moses", "Mosley",
        "Moss", "Mott", "Moulton", "Moya", "Moyer", "Mueller", "Muir", "Mullen",
        "Muller", "Mulligan", "Mullins", "Munoz", "Murdock", "Murphy", "Murray", "Murrell",
        "Musser", "Myers", "Myles", "Nabors", "Nadeau", "Nagel", "Nagy", "Najera",
        "Nakamura", "Nance", "Napier", "Nash", "Nasser", "Nathan", "Nava", "Navarro",
        "Naylor", "Neal", "Neeley", "Neely", "Neff", "Negron", "Nelson", "Ness",

        "Neumann", "Neville", "Newby", "Newell", "Newman", "Newsome", "Newton", "Ng",
        "Ngo", "Nguyen", "Nicholas", "Nichols", "Nicholson", "Nielsen", "Nielson", "Nieto",
        "Nieves", "Nix", "Nixon", "Noble", "Noel", "Nolan", "Noriega", "Norman",
        "Norris", "North", "Norton", "Norwood", "Novak", "Nowak", "Nowakowski", "Nunez",
        "Nye", "O'Brien", "O'Connell", "O'Connor", "O'Dell", "O'Donnell", "O'Hara", "O'Leary",
        "O'Malley", "O'Neal", "O'Neil", "O'Neill", "O'Reilly", "O'Rourke", "O'Shea", "O'Sullivan",
        "Oakes", "Oakley", "Oates", "Ochoa", "Odell", "Odom", "Ogden", "Oh",
        "Ojeda", "Okamoto", "Oldham", "Olsen", "Olson", "Oman", "Orellana", "Orlando",
        "Ornelas", "Orozco", "Orr", "Ortega", "Ortiz", "Osborn", "Osborne", "Osorio",
        "Otero", "Ott", "Otto", "Overton", "Owen", "Owens", "Pace", "Pacheco",

        "Packard", "Padilla", "Page", "Pagan", "Paine", "Painter", "Palmer", "Pantoja",
        "Paquette", "Paredes", "Parikh", "Parish", "Park", "Parker", "Parks", "Parrish",
        "Parsons", "Pascual", "Passmore", "Pate", "Patel", "Patrick", "Patterson", "Patton",
        "Paul", "Paulson", "Pavel", "Payne", "Paz", "Peacock", "Pearce", "Pearson",
        "Peck", "Peden", "Pedersen", "Peel", "Pena", "Pence", "Pendergrass", "Pendleton",
        "Penn", "Pennington", "Peralta", "Perea", "Perdue", "Perez", "Perkins", "Perry",
        "Peters", "Petersen", "Peterson", "Petit", "Petrov", "Pettit", "Petty", "Pham",
        "Phan", "Phelps", "Phillips", "Pickering", "Pickett", "Pierce", "Pierre", "Pierson",
        "Pike", "Pineda", "Pinkerton", "Pino", "Pinson", "Pinto", "Piper", "Pippin",
        "Pittman", "Pitts", "Platt", "Poe", "Pogue", "Polanco", "Polk", "Pollack",
        "Pollard", "Pollock", "Ponce", "Pond", "Poole", "Pope", "Porras", "Porter",
        "Posey", "Post", "Potter", "Potts", "Powell", "Powers", "Prado", "Prater",
        "Pratt", "Prescott", "Presley", "Preston", "Price", "Prieto", "Prince", "Pritchard",
        "Proctor", "Proulx", "Pruitt", "Pryor", "Puckett", "Pugh", "Pulido", "Purcell",
        "Purdy", "Purvis", "Putnam", "Qian", "Qiu", "Qualls", "Quan", "Queen",
        "Quesada", "Quezada", "Quick", "Quigley", "Quinlan", "Quinn", "Quinones", "Quintana",
        "Quintero", "Quiroz", "Raab", "Rader", "Radford", "Rafferty", "Ragan", "Ragland",
        "Ragsdale", "Rahman", "Raines", "Rains", "Raj", "Raleigh", "Raley", "Ralph",
        "Ralston", "Ramirez", "Ramos", "Ramsey", "Randall", "Randle", "Randolph", "Rangel",
        "Rao", "Rapp", "Rasmussen", "Ratcliff", "Rath", "Ratliff", "Rau", "Rawlings",
        "Rawls", "Ray", "Raymond", "Read", "Reagan", "Reardon", "Reaves", "Rector",

        "Redd", "Redding", "Reddy", "Redman", "Redmon", "Redmond", "Reece", "Reed",
        "Reeder", "Rees", "Reese", "Reeves", "Regan", "Reid", "Reilly", "Reimer",
        "Reina", "Reinhardt", "Reis", "Rendon", "Renner", "Reno", "Renteria", "Reyes",
        "Reyna", "Reynolds", "Rhee", "Rhoades", "Rhodes", "Rhyne", "Ricci", "Rice",
        "Rich", "Richard", "Richards", "Richardson", "Richey", "Richman", "Richmond", "Richter",
        "Rickard", "Ricker", "Ricketts", "Ricks", "Rico", "Riddle", "Rider", "Ridge",
        "Ridley", "Riegel", "Riel", "Riggs", "Riley", "Rinaldi", "Rinehart", "Ringer",
        "Rios", "Ripley", "Ritchie", "Ritter", "Rivas", "Rivera", "Rivers", "Roach",
        "Robbins", "Roberson", "Roberts", "Robertson", "Robey", "Robins", "Robinson", "Robles",
        "Robson", "Roca", "Rocha", "Roche", "Rock", "Rockwell", "Rodgers", "Rodrigues",
        "Rodriguez", "Roe", "Roeder", "Rogan", "Rogers", "Rojas", "Roland", "Rolfe",
        "Rollins", "Roman", "Romano", "Romero", "Romo", "Roper", "Roque", "Rosa",
        "Rosado", "Rosales", "Rosario", "Rosas", "Rose", "Rosen", "Rosenberg", "Rosenblatt",
        "Rosenfeld", "Rosenthal", "Ross", "Rossi", "Roth", "Rothschild", "Rouse", "Rousseau",
        "Rowan", "Rowe", "Rowell", "Rowland", "Rowley", "Roy", "Royal", "Royce",
        "Rubenstein", "Rubin", "Rubio", "Rucker", "Rudd", "Rudolph", "Rudy", "Ruffin",
        "Ruffino", "Ruiz", "Runyon", "Rupp", "Rush", "Rushing", "Rusk", "Russ",
        "Russell", "Russo", "Rust", "Rutherford", "Rutledge", "Ryan", "Ryder", "Saavedra",
        "Sabin", "Sacco", "Sadler", "Saeed", "Saenz", "Sager", "Sahni", "Saito",
        "Salas", "Salazar", "Salcedo", "Saleh", "Salerno", "Salgado", "Salinas", "Salisbury",
        "Salk", "Salmon", "Salter", "Sampson", "Samson", "Samuel", "Samuels", "Sanabria",
        "Sanchez", "Sandberg", "Sanders", "Sanderson", "Sandoval", "Sands", "Sanford", "Santamaria",
        "Santana", "Santiago", "Santos", "Sapp", "Sargent", "Sarmiento", "Sarno", "Sasser",
        "Sato", "Satterfield", "Saul", "Saunders", "Savage", "Savoy", "Sawyer", "Saylor",
        "Scales", "Scanlon", "Scarborough", "Schaefer", "Schafer", "Schaffer", "Schatz", "Scheffer",
        "Schell", "Schenk", "Scherer", "Schiller", "Schilling", "Schindler", "Schlegel", "Schlesinger",
        "Schmid", "Schmidt", "Schmitt", "Schmitz", "Schneider", "Schofield", "Scholl", "Schrader",
        "Schreiber", "Schroeder", "Schubert", "Schuler", "Schultz", "Schulz", "Schumacher", "Schuster",
        "Schwab", "Schwartz", "Schwarz", "Schweitzer", "Scoggins", "Scott", "Scroggins", "Scully",
        "Seabrook", "Seals", "Seaman", "Sears", "Seaton", "Seaver", "Sebastian", "Seeley",
        "Segal", "Seger", "Segovia", "Segura", "Seibert", "Seidel", "Seifert", "Seitz",
        "Self", "Sell", "Sellers", "Sells", "Selman", "Sena", "Senn", "Serna",
        "Serra", "Serrano", "Sessions", "Settle", "Sexton", "Seymour", "Shafer", "Shaffer",
        "Shah", "Shanahan", "Shane", "Shank", "Shannon", "Shao", "Shapiro", "Sharma",
        "Sharp", "Sharpe", "Shattuck", "Shaver", "Shaw", "Shea", "Shearer", "Sheehan",
        "Sheffield", "Sheldon", "Shelley", "Shelton", "Shen", "Shepard", "Shepherd", "Sheppard",
        "Sheridan", "Sherman", "Sherrill", "Sherrod", "Sherwood", "Shi", "Shields", "Shih",
        "Shilling", "Shim", "Shin", "Shine", "Shipley", "Shipman", "Shirley", "Shiver",
        "Shoemaker", "Shore", "Shores", "Short", "Shorter", "Showalter", "Shriver", "Shuey",
        "Shuler", "Shulman", "Shults", "Shultz", "Shumaker", "Shuman", "Shumate", "Shuster",
        "Sibley", "Siciliano", "Siebert", "Siegel", "Sierra", "Sievers", "Sigler", "Sikes",
        "Sikora", "Silva", "Silver", "Silverman", "Silvestri", "Simien", "Simmons", "Simms",
        "Simon", "Simonds", "Simons", "Simonsen", "Simonson", "Simpkins", "Simpson", "Sims",
        "Sinclair", "Singer", "Singh", "Singleton", "Sipes", "Sisk", "Sisson", "Sizemore",
        "Skaggs", "Skeen", "Skelton", "Skidmore", "Skinner", "Slade", "Slater", "Slaton",
        "Slaughter", "Sloan", "Small", "Smalley", "Smalls", "Smart", "Smedley", "Smiley",
        "Smith", "Smothers", "Smyth", "Sneed", "Snell", "Snider", "Snodgrass", "Snow",
        "Snowden", "Snyder", "Soares", "Solis", "Solomon", "Solorio", "Somers", "Sommer",
        "Sommers", "Song", "Sonnier", "Soper", "Sorensen", "Sorenson", "Soriano", "Soria",
        "Sosa", "Sotelo", "Soto", "Soule", "Sousa", "South", "Southerland", "Sowell",
        "Spade", "Spain", "Spangler", "Spann", "Sparks", "Sparrow", "Spaulding", "Spear",
        "Spears", "Specht", "Speck", "Speer", "Spence", "Spencer", "Sperry", "Spicer",
        "Spiegel", "Spivey", "Spooner", "Sprague", "Springer", "Sprouse", "Spruill", "Squires",
        "St. Clair", "St. John", "Stacey", "Stack", "Stacy", "Stafford", "Stahl", "Staley",
        "Stallings", "Stallworth", "Stamper", "Stamps", "Stanley", "Stanton", "Staples", "Stapleton",
        "Stark", "Starkey", "Starks", "Starling", "Starr", "Statham", "Staton", "Stauffer",
        "Stearns", "Steele", "Steen", "Stefan", "Stein", "Steinberg", "Steiner", "Stephan",
        "Stephens", "Stephenson", "Sterling", "Stern", "Stevens", "Stevenson", "Stewart", "Stiles",
        "Still", "Stillwell", "Stine", "Stinson", "Stitt", "Stock", "Stockman", "Stockton",
        "Stoddard", "Stoker", "Stokes", "Stoll", "Stone", "Stoner", "Storey", "Storm",
        "Story", "Stout", "Stovall", "Stover", "Stowe", "Stowers", "Strange", "Stratton",
        "Strauss", "Street", "Streeter", "Strickland", "Stringer", "Strong", "Stroud", "Stroup",
        "Stuart", "Stubbs", "Stuckey", "Sturgill", "Sturm", "Su", "Suarez", "Suggs",
        "Sullivan", "Summers", "Sumner", "Sun", "Sundberg", "Sung", "Sutherland", "Sutton",
        "Swain", "Swann", "Swanson", "Swartz", "Sweeney", "Sweet", "Swenson", "Swift",
        "Swindell", "Swisher", "Sykes", "Sylvester", "Szabo", "Szymanski", "Taber", "Tabor",
        "Tackett", "Taggart", "Tait", "Talbot", "Talbott", "Taliaferro", "Talley", "Tallman",
        "Tam", "Tamayo", "Tan", "Tanaka", "Tang", "Tanner", "Tapia", "Tapp",
        "Tarango", "Tarrant", "Tate", "Tatum", "Tavares", "Tavarez", "Taylor", "Teague",
        "Teal", "Teel", "Tejada", "Tejeda", "Tellez", "Temple", "Templeton", "Tennant",
        "Tenney", "Teran", "Terrell", "Terry", "Tessier", "Thacker", "Thao", "Tharp",
        "Thatcher", "Thayer", "Theriault", "Therrien", "Thibault", "Thibodeau", "Thiel", "Thiele",
        "Thigpen", "Thomas", "Thomason", "Thomasson", "Thompson", "Thorn", "Thorne", "Thornhill",
        "Thornton", "Thorpe", "Thrasher", "Thurman", "Thurston", "Tian", "Tibbetts", "Tice",
        "Tidwell", "Tierney", "Tiller", "Tilley", "Tillman", "Tilton", "Timm", "Timmerman",
        "Timmons", "Tindall", "Tinker", "Tinsley", "Tipton", "Tirado", "Titus", "Tobey",
        "Tobias", "Tobin", "Todd", "Tolbert", "Toledo", "Toler", "Toliver", "Tolliver",
        "Tom", "Tomas", "Tomlin", "Tomlinson", "Tompkins", "Toney", "Tong", "Toole",
        "Toomey", "Topper", "Toro", "Torres", "Toth", "Totten", "Tovar", "Tower",

        "Towers", "Towne", "Townes", "Towns", "Townsend", "Toy", "Tracey", "Tracy",
        "Trainor", "Tran", "Trapp", "Travers", "Travis", "Traxler", "Treadway", "Treadwell",
        "Trejo", "Tremblay", "Trent", "Trepanier", "Trevino", "Tribble", "Trimble", "Trinh",
        "Tripp", "Trivedi", "Trombley", "Trotter", "Trout", "Troutman", "Trowbridge", "Troy",

        "Troyer", "Truax", "Trudeau", "True", "Trujillo", "Trumbull", "Truong", "Tsai",
        "Tsang", "Tso", "Tsui", "Tu", "Tubbs", "Tucker", "Tully", "Tung",
        "Tunstall", "Turcotte", "Turek", "Turk", "Turley", "Turnbull", "Turner", "Turney",
        "Turpin", "Tuttle", "Twomey", "Tyas", "Tyler", "Tyner", "Tyree", "Tyrrell",
        "Tyson", "Uddin", "Ulloa", "Ullrich", "Ulmer", "Underwood", "Unger", "Upchurch",
        "Upton", "Urban", "Urbina", "Uribe", "Urquhart", "Urso", "Usher", "Utley",
        "Vaca", "Valadez", "Valdes", "Valdez", "Valdivia", "Valencia", "Valentin", "Valentine",
        "Valenzuela", "Valerio", "Valle", "Vallejo", "Valles", "Van", "Van Buren", "Van Cleave",
        "Van Dyke", "Van Horn", "Van Meter", "Van Ness", "Van Winkle", "Vance", "Vandal",
        "Vandenberg", "Vanderbilt", "Vargas", "Varner", "Vasquez", "Vaughan", "Vaughn", "Vazquez",
        "Vega", "Vela", "Velasco", "Velasquez", "Velez", "Vella", "Venable", "Ventura",
        "Vera", "Vergara", "Verma", "Vernon", "Vick", "Vickers", "Vidal", "Vieira",
        "Vigil", "Villa", "Villalobos", "Villalpando", "Villanueva", "Villarreal", "Villasenor", "Villegas",
        "Vincent", "Vinson", "Vinton", "Viola", "Vogt", "Voigt", "Voss", "Vu",
        "Wade", "Wadsworth", "Wagner", "Wagoner", "Wahl", "Wainwright", "Waite", "Wakefield",
        "Walden", "Waldo", "Waldron", "Walker", "Wall", "Wallace", "Waller", "Walling",

        "Wallis", "Walls", "Walsh", "Walston", "Walter", "Walters", "Walton", "Wang",
        "Ward", "Warden", "Ware", "Warfield", "Warner", "Warren", "Warwick", "Washington",
        "Watanabe", "Waters", "Watford", "Watkins", "Watson", "Watt", "Watters", "Watts",
        "Waugh", "Way", "Weaver", "Webb", "Webber", "Weber", "Webster", "Weddington",
        "Weed", "Weeks", "Weems", "Weese", "Wei", "Weil", "Weiner", "Weinstein",
        "Weir", "Weis", "Weisberg", "Weiss", "Welch", "Weldon", "Welker", "Weller",
        "Wells", "Welsh", "Wendel", "Wendt", "Wentworth", "Wentz", "Werner", "Wertz",
        "Wesley", "West", "Westbrook", "Wester", "Westfall", "Weston", "Wetzel", "Whalen",
        "Whaley", "Wharton", "Whatley", "Wheaton", "Wheeler", "Whelan", "Whipple", "Whitaker",
        "Whitcomb", "White", "Whitehead", "Whitehurst", "Whitely", "Whiteman", "Whiteside", "Whitfield",
        "Whiting", "Whitley", "Whitlock", "Whitman", "Whitmore", "Whitney", "Whitt", "Whittaker",

        "Whitten", "Whittington", "Whittle", "Whitworth", "Wicker", "Wickham", "Wicks", "Wiebe",
        "Wiegand", "Wieland", "Wiener", "Wiggins", "Wilbanks", "Wilbur", "Wilburn", "Wilcox",
        "Wilde", "Wilder", "Wiles", "Wiley", "Wilhelm", "Wilkerson", "Wilkes", "Wilkie",
        "Wilkins", "Wilkinson", "Will", "Willard", "Willett", "Williams", "Williamson", "Williford",
        "Willis", "Willoughby", "Wills", "Wilmot", "Wilson", "Wilt", "Wimmer", "Winchester",
        "Windham", "Windsor", "Wine", "Winfield", "Wing", "Winger", "Wingo", "Winkler",
        "Winn", "Winslow", "Winston", "Winter", "Winters", "Wirth", "Wise", "Wiseman",
        "Wisniewski", "Witham", "Withers", "Witherspoon", "Witt", "Witte", "Wix", "Wofford",
        "Wojcik", "Wolcott", "Wolf", "Wolfe", "Wolff", "Womack", "Wong", "Woo",
        "Wood", "Woodard", "Woodbury", "Woodcock", "Wooden", "Woodley", "Woodruff", "Woods",
        "Woodson", "Woodward", "Woodworth", "Woody", "Wooldridge", "Wooley", "Woolf", "Woolley",
        "Wooten", "Word", "Worden", "Workman", "Worley", "Worrall", "Worrell", "Worth",
        "Worthington", "Worthy", "Wray", "Wren", "Wright", "Wu", "Wunderlich", "Wyant",
        "Wyatt", "Wylie", "Wyman", "Wynn", "Wynne", "Xia", "Xiao", "Xie",
        "Xiong", "Xu", "Xue", "Yadav", "Yager", "Yamada", "Yamaguchi", "Yamamoto",
        "Yancey", "Yang", "Yanez", "Yao", "Yap", "Yarbrough", "Yates", "Ybarra",
        "Ye", "Yeager", "Yee", "Yen", "Yi", "Yin", "Yip", "Yoder",
        "Yoo", "Yoon", "York", "Yoshida", "Yost", "Youmans", "Young", "Youngblood",
        "Younger", "Yount", "Yu", "Yuan", "Yuen", "Yun", "Zabel", "Zabriskie",
        "Zaccaria", "Zachary", "Zahn", "Zajac", "Zak", "Zalewski", "Zaman", "Zambrano",
        "Zamora", "Zander", "Zane", "Zang", "Zanini", "Zapata", "Zaragoza", "Zarate",
        "Zavala", "Zayas", "Zea", "Zehnder", "Zeller", "Zeman", "Zentner", "Zerbe",
        "Zhang", "Zhao", "Zheng", "Zhou", "Zhu", "Ziegler", "Zielinski", "Zimmer",
        "Zimmerman", "Zink", "Zito", "Zoller", "Zook", "Zucker", "Zukowski", "Zuniga"
    };


    std::vector<std::string> titles = {"Dr.", "Prof.", "Dr.", "Prof.", "Dr."}; // More Dr. than Prof.

    std::vector<std::string> course_prefixes = {
        "Introduction to", "Advanced", "Fundamentals of", "Applied", "Theoretical",
        "Practical", "Modern", "Contemporary", "Principles of", "Topics in"
    };

    // Total count: 1000 course subjects
    std::vector<std::string> course_subjects = {
        "Algorithms", "Data Structures", "Database Systems", "Computer Networks",
        "Operating Systems", "Software Engineering", "Artificial Intelligence",
        "Machine Learning", "Computer Graphics", "Web Development", "Mobile Computing",
        "Cloud Computing", "Cybersecurity", "Distributed Systems", "Compiler Design",
        "Computer Architecture", "Human-Computer Interaction", "Data Mining",
        "Natural Language Processing", "Computer Vision", "Robotics", "Game Development",
        "Quantum Computing", "Blockchain", "Internet of Things", "Parallel Computing",
        "Discrete Mathematics", "Linear Algebra", "Calculus I", "Statistics",
        "Introduction to Programming", "Object-Oriented Programming", "Functional Programming",

        // --- Core CS & Theory ---
        "Advanced Algorithms", "Randomized Algorithms", "Approximation Algorithms", "Graph Algorithms",
        "Computational Geometry", "Theory of Computation", "Automata Theory", "Computability and Complexity",
        "Formal Languages", "Logic for Computer Science", "Programming Language Theory",
        "Type Theory", "Lambda Calculus", "Advanced Data Structures", "Algorithm Design and Analysis",
        "Information Theory", "Coding Theory", "Cryptographic Protocols", "Quantum Information Science",
        "Parameterized Complexity", "Computational Logic", "Model Checking", "Algorithm Engineering",

        // --- Systems & Architecture ---
        "Advanced Computer Architecture", "Multicore Architectures", "Memory Systems",
        "Embedded Systems", "Real-Time Operating Systems", "Advanced Operating Systems",
        "Virtualization and Cloud Infrastructure", "Network Protocols and Standards",
        "Wireless and Mobile Networks", "Network Security", "Software-Defined Networking",
        "High-Performance Computing", "Cluster Computing", "Grid Computing", "Fault-Tolerant Systems",
        "Storage Systems", "VLSI Design", "Digital Logic Design", "Microprocessor Systems",
        "Systems Programming", "Device Driver Development", "Performance Evaluation of Computer Systems",
        "Data Center Design", "Edge Computing", "Network Administration", "Systems Administration",

        // --- Software Engineering & Development ---
        "Software Design Patterns", "Software Testing and Quality Assurance", "Software Project Management",
        "Agile Software Development", "DevOps and Site Reliability Engineering", "Requirements Engineering",
        "Software Architecture and Design", "Formal Methods in Software Engineering",
        "Model-Driven Engineering", "Software Evolution and Maintenance", "Secure Software Development",
        "Component-Based Software Engineering", "Service-Oriented Architecture",
        "Microservices Architecture", "API Design and Management", "Continuous Integration/Continuous Deployment",
        "Version Control with Git", "Software Measurement and Metrics", "User Interface Engineering",

        // --- Artificial Intelligence & Machine Learning ---
        "Introduction to Artificial Intelligence", "Advanced Machine Learning", "Deep Learning",
        "Reinforcement Learning", "Neural Networks", "Probabilistic Graphical Models",
        "AI for Robotics", "Knowledge Representation and Reasoning", "Expert Systems",
        "Machine Learning for Healthcare", "AI Ethics and Society", "Computational Creativity",
        "Evolutionary Computation", "Swarm Intelligence", "Fuzzy Logic Systems", "AI Planning and Search",
        "Deep Reinforcement Learning", "Generative Adversarial Networks (GANs)", "Transformers and Attention Models",
        "Machine Learning Interpretability", "Federated Learning", "TinyML: ML on Embedded Devices",
        "Automated Machine Learning (AutoML)", "Causal Inference", "AI for Game Playing",

        // --- Data Science & Databases ---
        "Big Data Analytics", "Data Visualization", "Information Retrieval", "Advanced Database Systems",
        "NoSQL Databases", "Data Warehousing", "Business Intelligence", "Stream Processing",
        "Data Engineering", "Data Privacy and Security", "Scientific Data Management",
        "Graph Databases", "Time-Series Analysis", "Spatial Databases", "Multimedia Databases",
        "Data Cleaning and Preparation", "Predictive Modeling", "Statistical Learning",
        "Big Data Technologies: Hadoop and Spark", "Cloud Data Platforms", "Data Governance",

        // --- Graphics, Vision, & Interaction ---
        "Advanced Computer Graphics", "Real-Time Rendering", "Physically-Based Animation",
        "Computational Photography", "Geometric Modeling", "Visualization Techniques",
        "Augmented Reality", "Virtual Reality", "Advanced Human-Computer Interaction",
        "User Experience (UX) Design", "User Interface (UI) Design", "Accessibility in HCI",
        "3D User Interfaces", "Information Visualization", "Scientific Visualization",
        "Advanced Computer Vision", "3D Reconstruction", "Object Recognition", "Video Analysis",
        "Medical Image Analysis", "Biometrics", "Deep Learning for Vision",

        // --- Web, Mobile, & Cloud ---
        "Frontend Web Development", "Backend Web Development", "Full-Stack Web Development",
        "Web Frameworks (React, Angular, Vue)", "Server-side Scripting", "Web Security",
        "Progressive Web Apps", "iOS App Development", "Android App Development",
        "Cross-Platform Mobile Development", "Mobile UX/UI Design", "Cloud Native Application Development",
        "Serverless Computing", "Cloud Security and Compliance", "Cloud Management and Operations",
        "Web Assembly", "GraphQL", "Microfrontends", "Cloud Networking",

        // --- Security ---
        "Introduction to Cybersecurity", "Cryptography", "Applied Cryptography",
        "Ethical Hacking and Penetration Testing", "Digital Forensics", "Malware Analysis",
        "Security Operations and Incident Response", "Identity and Access Management",
        "Hardware Security", "Cyber-Physical Systems Security", "Reverse Engineering",
        "Application Security", "Privacy-Enhancing Technologies", "Blockchain Security",

        // --- Specialized & Emerging Topics ---
        "Bioinformatics", "Computational Biology", "Computational Finance", "E-commerce Technologies",
        "Digital Humanities", "Computational Social Science", "Legal Technology and Informatics",
        "Educational Technology", "Digital Art and Design", "Music Technology",
        "Game Engine Design", "Multiplayer Game Development", "Game Physics", "AI in Games",
        "Graphics for Games", "Robotic Motion Planning", "Autonomous Vehicles", "Drone Programming",
        "Control Systems", "Digital Signal Processing", "Quantum Error Correction", "Quantum Algorithms",

        // --- Mathematics ---
        "Calculus II", "Calculus III (Multivariable)", "Differential Equations", "Probability Theory",
        "Numerical Methods", "Optimization", "Graph Theory", "Combinatorics",
        "Number Theory", "Abstract Algebra", "Real Analysis", "Complex Analysis",
        "Topology", "Mathematical Logic", "Stochastic Processes", "Mathematical Modeling",
        "Financial Mathematics", "Actuarial Science", "Game Theory", "Control Theory",

        // --- Expanded Course Variations (Intro, Advanced, Labs, Seminars) ---
        "Introduction to Data Structures", "Algorithms Lab", "Database Systems Lab",
        "Operating Systems Lab", "Software Engineering Project I", "Software Engineering Project II",
        "Advanced Topics in AI", "Machine Learning Seminar", "Computer Graphics Project",
        "Advanced Web Applications", "Mobile Development Project", "Cybersecurity Lab",
        "Compiler Construction Lab", "Advanced Computer Networks", "Seminar in HCI",
        "Data Mining Project", "NLP with Deep Learning", "Computer Vision Lab", "Robotics Project",
        "Game Design and Development I", "Game Design and Development II", "Blockchain Applications",
        "IoT Systems Lab", "Parallel Programming Lab", "Discrete Mathematics II", "Applied Linear Algebra",
        "Probability and Statistics", "Introduction to Scientific Computing", "Capstone Project I",
        "Capstone Project II", "Honors Thesis in Computer Science", "Independent Study",
        "Research Methods in Computer Science", "Technical Communication", "Professional Ethics in Computing",
        "Introduction to Logic Design", "Digital Systems Lab", "Embedded Systems Project",
        "Network Programming", "Socket Programming", "Advanced Java Programming",
        "Advanced C++ Programming", "Python for Data Science", "R for Statistical Computing",
        "Scripting Languages (Perl/Python/Bash)", "Web Services", "RESTful API Development",
        "The C Programming Language", "Assembly Language Programming", "Firmware Development",
        "Data Analytics with Python", "Big Data Management Lab", "Cloud Solutions Architecture",
        "IT Infrastructure Management", "Penetration Testing Lab", "Forensics and Cyber Crime",
        "Cryptography and Network Security", "Information Security Management", "Social Engineering",
        "AI for Cybersecurity", "Biometric Security", "Computer Security Seminar",
        "Topics in Software Engineering", "Formal Verification of Software", "Software Refactoring",

        // --- Further Granularity & Niche Topics ---
        "Computational Neuroscience", "Systems Biology", "Cheminformatics", "Financial Engineering",
        "Algorithmic Trading", "Computational Economics", "Digital Forensics II", "Network Forensics",
        "Mobile Forensics", "Operating System Security", "Database Security", "Cloud Application Security",
        "IoT Security", "Human-Centered Security", "Usable Privacy and Security",
        "Cyber Law and Ethics", "Critical Infrastructure Protection", "Threat Intelligence",
        "Advanced Game AI", "Procedural Content Generation", "Virtual Reality Development Lab",
        "Augmented Reality Applications", "Haptic Interfaces", "Tangible User Interfaces",
        "Voice User Interface Design", "Collaborative and Social Computing", "Crowdsourcing Systems",
        "Geographic Information Systems (GIS)", "Remote Sensing", "3D Printing and Additive Manufacturing",
        "Sensor Networks", "Wearable Computing", "Brain-Computer Interfaces", "Computational Linguistics",
        "Speech Recognition and Synthesis", "Machine Translation", "Sentiment Analysis", "Information Extraction",
        "Dialogue Systems and Chatbots", "Deep Learning for NLP", "Statistical NLP",
        "Image and Video Processing", "Pattern Recognition", "Medical Imaging", "Robotic Perception",
        "Simultaneous Localization and Mapping (SLAM)", "Robot Kinematics and Dynamics",
        "Multi-Agent Systems", "Human-Robot Interaction", "Mobile Robotics Lab", "Autonomous Systems Lab",
        "Compiler Optimization", "Runtime Systems", "Program Analysis", "Interpreters and Virtual Machines",
        "GPU Architecture and Programming", "Domain-Specific Languages", "Advanced Compilers",
        "Introduction to Formal Methods", "Concurrency Theory", "Distributed Algorithms",
        "Peer-to-Peer Systems", "Blockchain and Cryptocurrencies", "Smart Contract Development",
        "Decentralized Applications (dApps)", "Web3 Foundations", "Content Delivery Networks",
        "Internet Measurements", "Network Management", "Optical Networks", "Data Center Networking",
        "Advanced Wireless Networks", "5G/6G Technology", "Mobile and Pervasive Computing",
        "Computer Organization", "Digital Computer Design", "RISC-V Architecture", "System-on-Chip (SoC) Design",
        "Reconfigurable Computing", "FPGA Programming", "Asynchronous Circuit Design",
        "Low-Power Design", "Computer Arithmetic", "Performance Modeling",
        "Queueing Theory", "Simulation Methods", "Statistical Quality Control", "Experimental Design",
        "Multivariate Analysis", "Bayesian Statistics", "Non-parametric Statistics", "Time Series Forecasting",
        "Survival Analysis", "Data Science for Business", "Marketing Analytics", "People Analytics",
        "Sports Analytics", "Computational Journalism", "Algorithmic Art", "Interactive Installations",
        "Sound Synthesis and Processing", "Introduction to DevOps", "Containerization with Docker",
        "Orchestration with Kubernetes", "Infrastructure as Code (Terraform, Ansible)",
        "Monitoring and Logging", "Reliability Engineering", "Software Process and Quality",
        "Global Software Engineering", "Empirical Software Engineering", "Human Factors in Software Engineering",
        "Cognitive Science for CS", "Philosophy of AI", "History of Computing", "Entrepreneurship for CS",
        "Product Management for Software", "Technical Writing for Engineers", "Introduction to Quantum Mechanics",
        "Linear Optimization", "Nonlinear Optimization", "Integer Programming", "Convex Optimization",
        "Stochastic Optimization", "Dynamic Programming", "Network Flows", "Matrix Computations",
        "Numerical Linear Algebra", "Numerical Analysis I", "Numerical Analysis II",
        "Partial Differential Equations", "Finite Element Method", "Monte Carlo Methods",
        "Fourier Analysis", "Wavelets and Signal Processing", "Set Theory", "Mathematical Proofs",
        "Category Theory for Programmers", "Homotopy Type Theory", "Information Retrieval and Web Search",
        "Recommender Systems", "Web Mining", "Social Network Analysis", "Data Fusion",
        "Knowledge Graphs", "Ontology Engineering", "Semantic Web Technologies",
        "Advanced SQL", "Database Tuning and Optimization", "Distributed Databases",
        "Transactional Systems", "Data Archiving and Preservation", "Foundations of Data Science",

        // --- Filling out to 1000 with more specific and interdisciplinary courses ---
        "Advanced Logic Design Lab", "Microcontroller Interfacing", "FPGA-Based System Design",
        "Cyber-Physical Systems Modeling", "Secure Coding Practices (C/C++)", "Secure Web Development",
        "Fuzz Testing and Vulnerability Discovery", "IoT Protocols and Communication",
        "Edge AI", "Cloud Cost Management", "Multi-Cloud Strategies", "Web Performance Optimization",
        "Advanced JavaScript Concepts", "TypeScript for Large Applications", "Mobile Game Development",
        "UI Animation and Motion Design", "Voice Interaction Design Lab", "HCI for AI Systems",
        "Explainable AI (XAI)", "AI Product Management", "Adversarial Machine Learning",
        "Privacy in Machine Learning", "Deep Learning for Audio", "Unsupervised Feature Learning",
        "Graph Neural Networks", "Self-Supervised Learning", "Causal Discovery",
        "Computational Advertising", "Financial Technology (FinTech)", "Regulatory Technology (RegTech)",
        "Precision Agriculture Technology", "Smart Cities Technology", "Digital Health",
        "Bioinformatics Algorithms", "Genomic Data Science", "Proteomics Informatics",
        "Structural Bioinformatics", "Systems and Network Medicine", "Computational Drug Discovery",
        "Game Theory for Networks", "Mechanism Design", "Algorithmic Game Theory",
        "Computational Social Choice", "Social and Information Networks", "Epidemic Modeling",
        "Advanced Animation Techniques", "Virtual Cinematography", "Shaders and Rendering Effects",
        "HCI for Development (ICT4D)", "Inclusive Design", "Affective Computing",
        "Color Theory and Application", "Typography for Digital Media", "Digital Fabrication",
        "Robotics: Perception and Planning", "Control of Mobile Robots", "Legged Robotics",
        "Soft Robotics", "Surgical Robotics", "Industrial Robotics and Automation",
        "Humanoid Robotics", "Advanced Operating Systems Design", "Kernel Hacking",
        "Distributed File Systems", "High-Throughput Computing", "Parallel I/O",
        "Energy-Efficient Computing", "Quantum Computing Hardware", "Quantum Cryptography",
        "Post-Quantum Cryptography", "Quantum Machine Learning", "Computational Complexity II",
        "Circuit Complexity", "Proof Complexity", "Structural Complexity", "Descriptive Complexity",
        "Advanced Automata Theory", "Formal Concept Analysis", "Symbolic Logic",
        "Metamathematics", "Model Theory", "Proof Theory", "Computability in Europe",
        "Mathematical Foundations of Computer Science", "Applied Category Theory", "Logic Programming with Prolog",
        "Constraint Logic Programming", "Functional Reactive Programming", "Dependently Typed Programming",
        "Concurrent Programming", "Programming for Parallel Architectures", "GPU Programming with CUDA",
        "OpenCL Programming", "Parallel Algorithms and Data Structures", "Software Transactional Memory",
        "Database System Implementation", "Query Processing and Optimization",
        "Physical Database Design", "Foundations of Blockchain", "Decentralized Finance (DeFi)",
        "Non-Fungible Tokens (NFTs) and the Metaverse", "Enterprise Blockchain",
        "Digital Identity Systems", "Wireless Sensor Network Lab", "Mobile Health (mHealth)",
        "Location-Based Services", "Network Simulation and Modeling", "Internet Economics",
        "Agile Project Management with Scrum", "Kanban for Software Teams", "Lean Software Development",
        "Code Review Best Practices", "Static and Dynamic Analysis", "Mutation Testing",
        "Behavior-Driven Development (BDD)", "Test-Driven Development (TDD)",
        "Refactoring to Patterns", "Microservices Testing Strategies", "Chaos Engineering",
        "API Security", "Cloud Native Security", "Container Security", "Offensive Security Tools",
        "Cybersecurity Threat Hunting", "Intelligence-Driven Defense", "Security Automation",
        "Industrial Control System (ICS) Security", "Automotive Security", "Aviation Cybersecurity",
        "Maritime Cybersecurity", "Space Systems Cybersecurity", "Scientific Writing",
        "Graduate Seminar I", "Graduate Seminar II", "Teaching Practicum in Computer Science",
        "Readings in Computer Graphics", "Readings in AI", "Readings in Systems",
        "Readings in Theory", "Topics in Computer Engineering", "Advanced Digital Forensics",
        "File System Analysis", "Memory Forensics", "Network Traffic Analysis",
        "Steganography and Steganalysis", "Anti-Forensics Techniques", "Social Media Forensics",
        "Cloud Forensics", "Legal Aspects of Digital Investigation", "Computer Science Education Research",
        "Cognitive Models of Programming", "Design of Programming Environments",
        "Technology in K-12 Education", "Learning Analytics", "Interactive Teaching with Technology",
        "The Digital Divide", "ICT Policy and Regulation", "Cyber Warfare and Espionage",
        "International Cybersecurity Policy", "Privacy Law and Data Protection", "Intellectual Property for Tech",
        "Open Source Software Licensing", "Tech Ethics and Public Policy", "AI and the Future of Work",
        "Sustainable Computing", "Green IT", "Computing for Social Good", "Humanitarian Engineering",
        "Technology for Emergency Response", "Introduction to UX Research", "User Interviews and Surveys",
        "Usability Testing", "Persona and Scenario Development", "Journey Mapping",
        "Information Architecture", "Wireframing and Prototyping", "Interaction Design",
        "Visual Design Principles", "Design Systems", "Advanced Prototyping Tools",
        "UX for Enterprise Applications", "UX for SaaS", "UX for Mobile", "UX for AI",
        "UX Writing and Content Strategy", "Service Design", "Speculative Design",
        "Applied Probability", "Stochastic Calculus for Finance", "Measure Theory",
        "Functional Analysis", "Galois Theory", "Algebraic Topology", "Differential Geometry",
        "Ring Theory", "Field Theory", "Lie Algebras", "Representation Theory",
        "Analytic Number Theory", "Algebraic Number Theory", "Diophantine Equations",
        "Probabilistic Method", "Extremal Combinatorics", "Enumerative Combinatorics",
        "Ramsey Theory", "Matroid Theory", "Sperner's Theory", "Design Theory", "Coding Theory II",
        "Information Theory and Statistics", "Statistical Signal Processing", "Image Reconstruction",
        "Inverse Problems", "Computational Electromagnetics", "Fluid Dynamics Simulation",
        "Molecular Dynamics", "Computational Chemistry", "Materials Informatics", "Climate Modeling",
        "Econometrics", "Operations Research", "Inventory Theory", "Scheduling Theory",
        "Supply Chain Management", "Decision Analysis", "Risk Analysis and Management",
        "Systems Simulation", "Monte Carlo Simulation for Science", "High Dimensional Data Analysis",
        "Topological Data Analysis", "Functional Data Analysis", "Spatiotemporal Data Analysis",
        "Causal Inference and Learning", "Ethics in Data Science", "Data Journalism",
        "Foundations of Quantum Computing", "Quantum Communication", "Quantum Sensing",
        "Integrated Photonics", "Nanoelectronics", "Advanced VLSI", "Power Electronics",
        "Robotics and Automation", "Mechatronics", "Control Systems Lab", "Digital Signal Processing Lab",
        "Capstone Design Project I", "Capstone Design Project II", "Technical Entrepreneurship",
        "Startup Engineering", "Venture Capital and Finance", "Growth Hacking",
        "Digital Marketing", "Leading Technical Teams", "Negotiation and Conflict Resolution",
        "The Business of Software", "Platform Strategy", "Network Effects", "Two-Sided Markets",
        "IT Governance and Strategy", "Enterprise Resource Planning (ERP) Systems",
        "Customer Relationship Management (CRM) Systems", "Business Process Management",
        "Digital Transformation", "IT Auditing and Controls", "Information Systems Strategy",
        "Introduction to Electrical Engineering", "Circuit Theory", "Electromagnetics",
        "Signals and Systems", "Electronics I", "Electronics II", "Solid State Devices",
        "Semiconductor Physics", "Analog Communication", "Digital Communication", "Antennas and Propagation",
        "Microwave Engineering", "Power Systems Analysis", "Robotics II",
        "Multi-robot Systems", "Swarm Robotics Lab", "Biologically Inspired Robotics",
        "Natural Language Understanding", "Conversational AI Lab", "AI for Social Impact",
        "Computational Sustainability", "Topics in Algorithmic Fairness",
        "Differential Privacy", "Secure Multi-Party Computation", "Homomorphic Encryption",
        "Modern Cryptography", "Complexity of Boolean Functions", "Communication Complexity",
        "Streaming Algorithms", "Sublinear Algorithms", "Property Testing", "Online Algorithms",
        "Geometric Data Structures", "Combinatorial Optimization", "Integer and Combinatorial Optimization",
        "Network Design", "Approximation Algorithms for NP-hard Problems", "Advanced Data Analysis",
        "Statistical Methods for Machine Learning", "Bayesian Machine Learning", "Kernel Methods",
        "Gaussian Processes", "Probabilistic Programming", "Meta-Learning", "Few-Shot Learning",
        "Zero-Shot Learning", "Continual Learning", "Graph Representation Learning",
        "Dynamic and Temporal Graphs", "Geometric Deep Learning", "3D Vision", "Video Understanding",
        "Action Recognition", "Multimodal Machine Learning", "Visual Question Answering",
        "Image Captioning", "Audio-Visual Learning", "Embodied AI", "AI for Autonomous Driving",
        "AI in Healthcare: Diagnostics", "AI in Healthcare: Treatment", "Computational Genomics",
        "Machine Learning for Drug Discovery", "AI in Finance: Markets and Trading",
        "Robo-Advising and Wealth Management", "AI for Climate Change Mitigation",
        "Computational Models of Language", "Discourse and Dialogue", "Pragmatics",
        "Phonetics and Phonology", "Syntax and Parsing", "Semantics and Lexicology",
        "Historical Linguistics", "Corpus Linguistics", "Programming for Linguists",
        "Final Year Project - Part A", "Final Year Project - Part B", "Internship", "Co-op Work Term",
        "Undergraduate Research Opportunity", "Directed Studies in Computer Science",
        "Honors Seminar", "Special Topics in Computer Science I", "Special Topics in Computer Science II",
        "Advanced Topics in Algorithms", "Advanced Topics in Theory of Computation",
        "Advanced Topics in Computer Architecture", "Advanced Topics in Networks",
        "Advanced Topics in Programming Languages", "Advanced Topics in Security",
        "Advanced Topics in Databases", "Advanced Topics in Graphics and Vision",
        "Advanced Topics in Software Systems", "Advanced Topics in Robotics", "Introduction to Philosophy",
        "Cognitive Psychology", "Linear Circuits", "Introduction to Mechanical Engineering",
        "Thermodynamics", "Statics and Dynamics", "Materials Science",
        "Fundamentals of Public Speaking", "Intercultural Communication", "Organizational Behavior",
        "Principles of Economics", "Microeconomics", "Macroeconomics", "Financial Accounting",
        "Managerial Accounting", "Corporate Finance", "Marketing Principles", "Operations Management"
    };

    std::vector<std::string> room_types = {"Room", "Lab", "Lecture Hall", "Seminar Room", "Tutorial Room"};

public:
    SchedulingDataGenerator(unsigned int seed = std::chrono::steady_clock::now().time_since_epoch().count());

    SchedulingData generateData(
        int num_lecturers,
        int num_groups,
        int num_rooms,
        int num_courses,
        int days = 5,
        int periods_per_day = 8,
        double undesirable_slot_probability = 0.15, // Probability a lecturer/group has undesirable slots
        double course_feature_probability = 0.3, // Probability a course needs special features
        double room_feature_probability = 0.4 // Probability a room has special features
    );

private:
    std::vector<Lecturer> generateLecturers(int count, int days, int periods_per_day, double undesirable_prob);

    std::vector<StudentGroup> generateStudentGroups(int count, int days, int periods_per_day, double undesirable_prob);

    std::vector<Room> generateRooms(int count, int num_groups, double feature_prob);

    std::vector<Course> generateCourses(int count, int num_lecturers, int num_groups, double feature_prob);
};

#endif //SCHEDULING_DATA_GENERATOR_H
